### ISSUE TITLE
CI Support

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/Akka.Persistence.Sqlite#2]
cc @Horusiath - is there anything special I need to add to the build server to make this work? Or will all of the Sqllite binaries be added automatically via NuGet? Asking so I can see if I can fit this into https://github.com/akkadotnet/akka.net/issues/1193

**Comment by Horusiath** [comment]
When I worked on the project, the only necessary dependency (except Akka ofc) was `System.Data.SQLite.Core`. No additional dll's were needed.
